<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masterstorge.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StorageRecordsProto</code>
 */
class StorageRecordsProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .StorageRecordProto storage_records = 1;</code>
     */
    private $storage_records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protos\StorageRecordProto[]|\Google\Protobuf\Internal\RepeatedField $storage_records
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Masterstorge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .StorageRecordProto storage_records = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStorageRecords()
    {
        return $this->storage_records;
    }

    /**
     * Generated from protobuf field <code>repeated .StorageRecordProto storage_records = 1;</code>
     * @param \App\Protos\StorageRecordProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStorageRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\StorageRecordProto::class);
        $this->storage_records = $arr;

        return $this;
    }

}

