<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masterstorge.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BaseModel</code>
 */
class BaseModel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint64 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>
     */
    protected $uuid = null;
    /**
     * Generated from protobuf field <code>optional uint64 ext_created_by_id = 3;</code>
     */
    protected $ext_created_by_id = null;
    /**
     * Generated from protobuf field <code>optional string created_at = 4;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>optional string updated_at = 5;</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>optional int32 ordering = 6;</code>
     */
    protected $ordering = null;
    /**
     * Generated from protobuf field <code>optional bool hidden = 7;</code>
     */
    protected $hidden = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $uuid
     *     @type int|string $ext_created_by_id
     *     @type string $created_at
     *     @type string $updated_at
     *     @type int $ordering
     *     @type bool $hidden
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Masterstorge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>
     * @return string
     */
    public function getUuid()
    {
        return isset($this->uuid) ? $this->uuid : '';
    }

    public function hasUuid()
    {
        return isset($this->uuid);
    }

    public function clearUuid()
    {
        unset($this->uuid);
    }

    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 ext_created_by_id = 3;</code>
     * @return int|string
     */
    public function getExtCreatedById()
    {
        return isset($this->ext_created_by_id) ? $this->ext_created_by_id : 0;
    }

    public function hasExtCreatedById()
    {
        return isset($this->ext_created_by_id);
    }

    public function clearExtCreatedById()
    {
        unset($this->ext_created_by_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 ext_created_by_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExtCreatedById($var)
    {
        GPBUtil::checkUint64($var);
        $this->ext_created_by_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string created_at = 4;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return isset($this->created_at) ? $this->created_at : '';
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>optional string created_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string updated_at = 5;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return isset($this->updated_at) ? $this->updated_at : '';
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>optional string updated_at = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 ordering = 6;</code>
     * @return int
     */
    public function getOrdering()
    {
        return isset($this->ordering) ? $this->ordering : 0;
    }

    public function hasOrdering()
    {
        return isset($this->ordering);
    }

    public function clearOrdering()
    {
        unset($this->ordering);
    }

    /**
     * Generated from protobuf field <code>optional int32 ordering = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOrdering($var)
    {
        GPBUtil::checkInt32($var);
        $this->ordering = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool hidden = 7;</code>
     * @return bool
     */
    public function getHidden()
    {
        return isset($this->hidden) ? $this->hidden : false;
    }

    public function hasHidden()
    {
        return isset($this->hidden);
    }

    public function clearHidden()
    {
        unset($this->hidden);
    }

    /**
     * Generated from protobuf field <code>optional bool hidden = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->hidden = $var;

        return $this;
    }

}

