<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masterstorge.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StorageRecordProto</code>
 */
class StorageRecordProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint64 storage_id = 1;</code>
     */
    protected $storage_id = null;
    /**
     * Generated from protobuf field <code>optional string value = 2;</code>
     */
    protected $value = null;
    /**
     * Generated from protobuf field <code>optional int64 created = 3;</code>
     */
    protected $created = null;
    /**
     * Generated from protobuf field <code>optional int64 updated = 4;</code>
     */
    protected $updated = null;
    /**
     * Generated from protobuf field <code>optional int64 deleted = 5;</code>
     */
    protected $deleted = null;
    /**
     * Generated from protobuf field <code>optional .BaseModel base_model = 6;</code>
     */
    protected $base_model = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $storage_id
     *     @type string $value
     *     @type int|string $created
     *     @type int|string $updated
     *     @type int|string $deleted
     *     @type \App\Protos\BaseModel $base_model
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Masterstorge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint64 storage_id = 1;</code>
     * @return int|string
     */
    public function getStorageId()
    {
        return isset($this->storage_id) ? $this->storage_id : 0;
    }

    public function hasStorageId()
    {
        return isset($this->storage_id);
    }

    public function clearStorageId()
    {
        unset($this->storage_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 storage_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStorageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->storage_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : '';
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>optional string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 created = 3;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return isset($this->created) ? $this->created : 0;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     * Generated from protobuf field <code>optional int64 created = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 updated = 4;</code>
     * @return int|string
     */
    public function getUpdated()
    {
        return isset($this->updated) ? $this->updated : 0;
    }

    public function hasUpdated()
    {
        return isset($this->updated);
    }

    public function clearUpdated()
    {
        unset($this->updated);
    }

    /**
     * Generated from protobuf field <code>optional int64 updated = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 deleted = 5;</code>
     * @return int|string
     */
    public function getDeleted()
    {
        return isset($this->deleted) ? $this->deleted : 0;
    }

    public function hasDeleted()
    {
        return isset($this->deleted);
    }

    public function clearDeleted()
    {
        unset($this->deleted);
    }

    /**
     * Generated from protobuf field <code>optional int64 deleted = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BaseModel base_model = 6;</code>
     * @return \App\Protos\BaseModel|null
     */
    public function getBaseModel()
    {
        return $this->base_model;
    }

    public function hasBaseModel()
    {
        return isset($this->base_model);
    }

    public function clearBaseModel()
    {
        unset($this->base_model);
    }

    /**
     * Generated from protobuf field <code>optional .BaseModel base_model = 6;</code>
     * @param \App\Protos\BaseModel $var
     * @return $this
     */
    public function setBaseModel($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\BaseModel::class);
        $this->base_model = $var;

        return $this;
    }

}

