<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masterstorge.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StorgeSyncRecord</code>
 */
class StorgeSyncRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string value = 1;</code>
     */
    protected $value = null;
    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     */
    protected $key = null;
    /**
     * Generated from protobuf field <code>optional uint64 user_id = 3;</code>
     */
    protected $user_id = null;
    /**
     * Generated from protobuf field <code>repeated .StorageRecord storage_records = 4;</code>
     */
    private $storage_records;
    /**
     * Generated from protobuf field <code>optional string email = 5;</code>
     */
    protected $email = null;
    /**
     * Generated from protobuf field <code>optional uint64 id = 6;</code>
     */
    protected $id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *     @type string $key
     *     @type int|string $user_id
     *     @type \App\Protos\StorageRecord[]|\Google\Protobuf\Internal\RepeatedField $storage_records
     *     @type string $email
     *     @type int|string $id
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Masterstorge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : '';
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>optional string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return isset($this->key) ? $this->key : '';
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return isset($this->user_id) ? $this->user_id : 0;
    }

    public function hasUserId()
    {
        return isset($this->user_id);
    }

    public function clearUserId()
    {
        unset($this->user_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .StorageRecord storage_records = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStorageRecords()
    {
        return $this->storage_records;
    }

    /**
     * Generated from protobuf field <code>repeated .StorageRecord storage_records = 4;</code>
     * @param \App\Protos\StorageRecord[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStorageRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\StorageRecord::class);
        $this->storage_records = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return isset($this->email) ? $this->email : '';
    }

    public function hasEmail()
    {
        return isset($this->email);
    }

    public function clearEmail()
    {
        unset($this->email);
    }

    /**
     * Generated from protobuf field <code>optional string email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 6;</code>
     * @return int|string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

}

